#!/usr/bin/env python3
"""
gen_kinematics_reference.py - independent URDF forward kinematics for the Unity
kinematics gate.

Emits kinematics_reference.json: for each of three joint poses, every link's origin
expressed in the PELVIS frame, in the ISAAC frame. The Unity PlayMode test commands
the same joint angles, reads each link's position back through
pelvis.InverseTransformPoint(), maps it to Isaac, and requires agreement < 1 mm.

The FK here is rebuilt from the URDF's joint origins and axes, NOT from
IsaacH1_rig.json, so a sign error in the frame map or an inverted anchor cannot
cancel out on both sides.
"""
import json, os, sys
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rig_audit import UrdfFK

HERE = os.path.dirname(os.path.abspath(__file__))
EX = os.path.normpath(os.path.join(HERE, '..', '..', 'h1'))

rig = json.load(open(os.path.join(HERE, 'IsaacH1_rig.json')))
fk = UrdfFK(os.path.join(EX, 'robot', 'h1.urdf'))
jorder = rig['jointOrder']
jinfo = {b['joint']['name']: b['joint'] for b in rig['bodies'] if b.get('joint')}

def clampd(name, v):
    lo, hi = jinfo[name]['lowerRad'], jinfo[name]['upperRad']
    return float(min(max(v, lo + 1e-3), hi - 1e-3))

poses = []
# 1. zero pose
poses.append(('zero', {j: 0.0 for j in jorder}))
# 2. the Isaac default (spawn) pose
poses.append(('default', {j: jinfo[j]['defaultPosRad'] for j in jorder}))
# 3. an asymmetric pose that exercises every axis and both signs, inside the limits
rng = np.random.default_rng(20260827)
asym = {}
for i, j in enumerate(jorder):
    lo, hi = jinfo[j]['lowerRad'], jinfo[j]['upperRad']
    # deterministic spread across each joint's own range, alternating sign
    frac = 0.35 + 0.30 * ((i * 7) % 5) / 4.0
    asym[j] = clampd(j, (hi if i % 2 == 0 else lo) * frac)
poses.append(('asymmetric', asym))

out = {'_comment': ('Independent URDF forward kinematics. Link origins in the PELVIS '
                    'frame, ISAAC convention (right-handed, Z-up, metres). Generated by '
                    'gen_kinematics_reference.py; the Unity gate is < 1 mm.'),
       'bodyOrder': rig['bodyOrder'], 'jointOrder': jorder, 'poses': []}

for name, q in poses:
    P = fk.fk(q)
    root = P['pelvis'][0]
    Rroot = P['pelvis'][1]
    entry = {'name': name,
             'jointPosRad': [round(q[j], 9) for j in jorder],
             'linkPosInPelvisIsaac': []}
    for bn in rig['bodyOrder']:
        rel = Rroot.T @ (P[bn][0] - root)
        entry['linkPosInPelvisIsaac'].append([round(float(v), 9) for v in rel])
    out['poses'].append(entry)

with open(os.path.join(HERE, 'kinematics_reference.json'), 'w', newline='\n') as f:
    json.dump(out, f, indent=2); f.write('\n')

print('wrote kinematics_reference.json')
for p in out['poses']:
    span = np.array(p['linkPosInPelvisIsaac'])
    print(f"  pose '{p['name']:11s}' joints[min,max]=[{min(p['jointPosRad']):+.3f},"
          f"{max(p['jointPosRad']):+.3f}]  link extent z=[{span[:,2].min():+.3f},{span[:,2].max():+.3f}]")
