"""Articulation configuration for the Boy.

Every number here is READ from ``boy_rig.json`` (written by ``ISAAC/boy_rig/build_boy_rig.py``)
so the Isaac side and the Unity side share one source of truth: joint order, default pose,
gains, effort limits, spawn height. If you want to change a gain, change it in
``build_boy_rig.py`` and re-run it - do not edit this file.

The USD itself (``boy.usda``) is the headless articulation: primitive collision shapes only,
no visual meshes. Set ``BOY_RIG_DIR`` to point at a different ``out/`` folder.
"""

from __future__ import annotations

import json
import os

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg

_HERE = os.path.dirname(os.path.abspath(__file__))
BOY_RIG_DIR = os.environ.get(
    "BOY_RIG_DIR", os.path.normpath(os.path.join(_HERE, "..", "..", "boy_rig", "out"))
)
BOY_USD_PATH = os.path.join(BOY_RIG_DIR, "boy.usda")
BOY_RIG_JSON = os.path.join(BOY_RIG_DIR, "boy_rig.json")

if not os.path.exists(BOY_RIG_JSON):
    raise FileNotFoundError(
        f"{BOY_RIG_JSON} not found. Run `python ISAAC/boy_rig/build_boy_rig.py` first, or set BOY_RIG_DIR."
    )

with open(BOY_RIG_JSON, "r", encoding="utf-8") as _f:
    BOY_RIG = json.load(_f)

_JOINTS = [b["joint"] for b in BOY_RIG["bodies"] if b.get("joint")]
JOINT_NAMES = [j["name"] for j in _JOINTS]
DEFAULT_JOINT_POS = {j["name"]: float(j["defaultPosRad"]) for j in _JOINTS}
JOINT_FAMILY = {j["name"]: j["family"] for j in _JOINTS}

# actuator groups: legs / feet / spine / arms, each an ImplicitActuator (PhysX drive)
_GROUPS = {
    "legs": ("hip_yaw", "hip_roll", "hip_pitch", "knee"),
    "feet": ("ankle_pitch", "ankle_roll"),
    "spine": ("spine_pitch",),
    "arms": ("shoulder_roll", "shoulder_pitch", "shoulder_yaw", "elbow"),
}


def _group_cfg(families):
    names = [j["name"] for j in _JOINTS if j["family"] in families]
    return ImplicitActuatorCfg(
        joint_names_expr=names,
        effort_limit_sim={j["name"]: float(j["effortLimit"]) for j in _JOINTS if j["family"] in families},
        stiffness={j["name"]: float(j["stiffness"]) for j in _JOINTS if j["family"] in families},
        damping={j["name"]: float(j["damping"]) for j in _JOINTS if j["family"] in families},
        armature={j["name"]: float(j["armature"]) for j in _JOINTS if j["family"] in families},
    )


BOY_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=BOY_USD_PATH,
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=False,
            retain_accelerations=False,
            linear_damping=float(BOY_RIG["physics"]["linearDamping"]),
            angular_damping=float(BOY_RIG["physics"]["angularDamping"]),
            max_linear_velocity=float(BOY_RIG["physics"]["maxLinearVelocity"]),
            max_angular_velocity=float(BOY_RIG["physics"]["maxAngularVelocity"]),
            max_depenetration_velocity=float(BOY_RIG["physics"]["maxDepenetrationVelocity"]),
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=bool(BOY_RIG["physics"]["enabledSelfCollisions"]),
            solver_position_iteration_count=int(BOY_RIG["physics"]["solverPositionIterations"]),
            solver_velocity_iteration_count=int(BOY_RIG["physics"]["solverVelocityIterations"]),
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=tuple(float(v) for v in BOY_RIG["spawn"]["posIsaac"]),
        joint_pos=dict(DEFAULT_JOINT_POS),
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.9,
    actuators={name: _group_cfg(fams) for name, fams in _GROUPS.items()},
)
"""The Boy: 22 links, 21 revolute joints, 45 kg, T-pose zero, default pose from boy_rig.json."""
